// This file is generated by packages/reference/scripts/build.mjs

export type ReferenceDoc = {
  slug: string;
  title: string;
  body: string;
  order?: number;
};

export type ReferenceNavItem = Pick<ReferenceDoc, "slug" | "title" | "order">;

export declare const referenceDocs: Record<string, ReferenceDoc>;
export declare const referenceNav: Array<ReferenceNavItem>;
export declare function getReferenceDoc(slug: string): ReferenceDoc | null;
declare const _default: typeof referenceNav;
export default _default;
