// Auto-generated by scripts/generate-std-raw.ts. Do not edit manually.
// This module is only used in the browser when import.meta.glob is not transformed
// (e.g., linked dependency not processed by the consumer's Vite pipeline).
// It statically imports the std files as raw strings so bundlers pre-bundle them.

// Note: add declarations for '*.voyd?raw' in types to satisfy TS.
import array from "../../../std/array.voyd?raw";
import fixed_array from "../../../std/fixed_array.voyd?raw";
import index from "../../../std/index.voyd?raw";
import iter from "../../../std/iter.voyd?raw";
import linear_memory from "../../../std/linear_memory.voyd?raw";
import macros from "../../../std/macros.voyd?raw";
import map from "../../../std/map.voyd?raw";
import msg_pack_decoder from "../../../std/msg_pack/decoder.voyd?raw";
import msg_pack_encoder from "../../../std/msg_pack/encoder.voyd?raw";
import msg_pack_index from "../../../std/msg_pack/index.voyd?raw";
import operators from "../../../std/operators.voyd?raw";
import optional from "../../../std/optional.voyd?raw";
import string from "../../../std/string.voyd?raw";
import utils from "../../../std/utils.voyd?raw";
import vsx from "../../../std/vsx.voyd?raw";

export const stdRaw: Record<string, string> = {
  "std/array.voyd": array,
  "std/fixed_array.voyd": fixed_array,
  "std/index.voyd": index,
  "std/iter.voyd": iter,
  "std/linear_memory.voyd": linear_memory,
  "std/macros.voyd": macros,
  "std/map.voyd": map,
  "std/msg_pack/decoder.voyd": msg_pack_decoder,
  "std/msg_pack/encoder.voyd": msg_pack_encoder,
  "std/msg_pack/index.voyd": msg_pack_index,
  "std/operators.voyd": operators,
  "std/optional.voyd": optional,
  "std/string.voyd": string,
  "std/utils.voyd": utils,
  "std/vsx.voyd": vsx,
};
